spring:
  datasource:
    druid:
      master-test:
        username: root
        password: ******
        url: jdbc:mysql://127.0.0.1:3306/master_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
      slave-test:
        username: root
        password: ******
        url: jdbc:mysql://127.0.0.1:3306/slave_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: swagger
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.springframework.web: debug




